"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Page Layout",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const path = usePathname();
  //alert(path);

  // const isActive =

  const navLinks = [
    { navName: "Login", navHref: "/login" },
    { navName: "Signup", navHref: "/signup" }
  ]

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-emerald-800 p-4">
          <h1>Nested Header</h1>

          {
            navLinks.map((a) => {
              return (
                <Link href={a.navHref} key={a.navHref} className={path == a.navHref ? "text-blue-400 font-bold p-2 border-b-2 border-amber-50" : "font-bold p-2"}>{a.navName}</Link>
              )
            })
          }

          {/* <Link href={"/login"} className={path == "/login" ? "text-blue-400 font-bold" : ""}>Login</Link>
          <Link href={"/signup"} className={path == "/signup" ? "text-blue-400 font-bold" : ""}> Sign Up</Link> */}
        </header>
        {children}

        <footer className="bg-orange-800 p-4">
          <p>Nested Footer</p>
        </footer>
      </body>
    </html >
  );
}
