import { Metadata } from 'next';
import React from 'react'
import Counter from './Counter';

export const metadata: Metadata = {
    title: "Counter",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <Counter />
    )
}
